name: rye-flex-opt-pyomo
dependencies:
  - python=3.7
  - certifi=2020.11.8
  - pip=20.2.4
  - setuptools=46.0.0=py37_0
  - wheel=0.35.1
  - cachemeorg::glpk==4.57
  - cachemeorg::ipopt_bin==3.7.1
  - pip:
      - nose==1.3.7
      - ply==3.11
      - Pyomo==5.7.1
      - PyUtilib==6.0.0
      - six==1.15.0
      - -e .
